version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
<<<<<<< Updated upstream
=======
    allow:
      - dependency-type: "all"
    assignees:
      - "ctdfo"
>>>>>>> Stashed changes
